gencode_gene:
  path: gencode/gene
  nodes: True
  edges: False

gencode_transcripts:
  path: gencode/transcript
  nodes: True
  edges: True

gencode_exon:
  path: gencode/exon
  nodes: True
  edges: False

uniprotkb:
  path: uniprot
  nodes: True
  edges: True

pathway:
  path: reactome
  nodes: True
  edges: True

gaf:
  path: gaf
  nodes: False
  edges: True

tflink:
  path: tflink
  nodes: False
  edges: True

string:
  path: string
  nodes: False
  edges: True

tadmap:
  path: tadmap
  nodes: True
  edges: True

gtex_eqtl:
  path: gtex/eqtl
  nodes: False
  edges: True

abc:
  path: abc
  nodes: False
  edges: True

cadd:
  path: cadd
  nodes: True
  edges: False

refseq_closest_gene:
  path: refseq
  nodes: False
  edges: True

epd_promoter:
  path: epd
  nodes: True
  edges: True

peregrine_enhancer:
  path: peregrine
  nodes: True
  edges: True

dbsuper_super_enhancer:
  path: dbsuper
  nodes: True
  edges: True

dbsnp:
  path: dbsnp
  nodes: True
  edges: False

enhancer_atlas_enhancer:
  path: enhancer_atlas
  nodes: False
  edges: True

pgboost:
  path: pgboost
  nodes: False
  edges: True

motif_diff:
  path: motif_diff
  nodes: False
  edges: True

ccre_enhancer:
  path: ccre/enhancer_ccre
  nodes: True
  edges: True

ccre_promoter:
  path: ccre/promoter_ccre
  nodes: True
  edges: True

encode_tfbs:
  path: tfbs
  nodes: True
  edges: True

biological_process:
  path: gene_ontology/biological_process
  nodes: True
  edges: True

molecular_function:
  path: gene_ontology/molecular_function
  nodes: True
  edges: True

cellular_component:
  path: gene_ontology/cellular_component
  nodes: True
  edges: True

gene_ontology:
  path: gene_ontology
  nodes: True
  edges: True

uberon:
  path: uberon
  nodes: True
  edges: True

cell_line_ontology:
  path: cell_line_ontology
  nodes: True
  edges: True

cell_ontology:
  path: cell_ontology
  nodes: True
  edges: True

experimental_factor_ontology:
  path: experimental_factor_ontology
  nodes: True
  edges: True

brenda_tissue_ontology:
  path: brenda_tissue_ontology
  nodes: True
  edges: True

tf_snp:
  path: tf_snp
  nodes: False
  edges: True